# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='linenumber',
            new_name='line_number',
        ),
    ]
