# Generated by Django 2.0.7 on 2018-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0003_ocurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocurrence',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
