# Generated by Django 2.0.7 on 2018-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0005_auto_20180707_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocurrence',
            name='finish_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='notes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='response_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='successfull',
            field=models.NullBooleanField(default=None),
        ),
    ]
