# Generated by Django 2.0.7 on 2018-07-08 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0007_auto_20180707_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocurrence',
            name='finish_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
