# Generated by Django 2.0.7 on 2018-07-08 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0009_auto_20180707_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocurrence',
            name='responder_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
