# Generated by Django 2.0.7 on 2018-07-08 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0010_auto_20180707_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocurrence',
            name='finish_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='responder_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='response_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='successfull',
            field=models.BooleanField(),
        ),
    ]
