# Generated by Django 2.0.7 on 2018-07-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0013_auto_20180707_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocurrence',
            old_name='busid',
            new_name='bus',
        ),
    ]
