# Generated by Django 2.0.7 on 2018-07-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0014_auto_20180707_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocurrence',
            old_name='responder_id',
            new_name='responder',
        ),
    ]
