# Generated by Django 2.0.7 on 2018-07-08 01:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CTGerson', '0015_auto_20180707_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ocurrence',
            new_name='Occurrence',
        ),
    ]
