# Generated by Django 2.0.7 on 2018-07-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0017_auto_20180707_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
