# Generated by Django 2.0.7 on 2018-07-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0020_auto_20180707_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={},
        ),
    ]
