# Generated by Django 2.0.7 on 2018-07-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0021_auto_20180707_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'permissions': (('can_see_bus_list', 'See bus list'),)},
        ),
    ]
