# Generated by Django 2.0.7 on 2018-07-10 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0025_meshblu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='alert_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
