# Generated by Django 2.0.7 on 2018-07-10 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CTGerson', '0027_auto_20180709_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
